#!/usr/bin/env bash
# scripts/loop/ci_verify.sh
# One-time pre-kickoff check that GitHub Actions CI fires + passes for
# integration/perf-roadmap. Round-2 M-8 + round-3 M-6: SHA-pinned,
# wait-for-completion.
#
# Usage: scripts/loop/ci_verify.sh
# Exit codes:
#   0 — CI run for the trigger SHA reached `success`
#   1 — CI run reached non-success terminal status
#   2 — `gh` CLI not configured / not authenticated
#   3 — timeout (30 min) waiting for CI

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

if ! command -v gh >/dev/null 2>&1; then
  echo "FAIL: gh CLI not found. Install via: brew install gh" >&2
  exit 2
fi
if ! gh auth status >/dev/null 2>&1; then
  echo "FAIL: gh CLI not authenticated. Run: gh auth login" >&2
  exit 2
fi

if [[ "$(git rev-parse --abbrev-ref HEAD)" != "integration/perf-roadmap" ]]; then
  echo "FAIL: not on integration/perf-roadmap" >&2
  exit 1
fi

echo "Triggering trivial change to verify CI fires + passes…"
echo "" >> diagnostic/_state.md
git add diagnostic/_state.md
git commit -m "ci: trigger workflow verification [no-op]

Generated by scripts/loop/ci_verify.sh — confirms GitHub Actions fires
on integration/perf-roadmap pushes before the autonomous loop kicks off.
"
git push
TRIGGER_SHA=$(git rev-parse HEAD)
echo "Trigger SHA: $TRIGGER_SHA"

DEADLINE=$(( $(date +%s) + 1800 ))   # 30 min budget
echo "Polling for run with headSha=$TRIGGER_SHA (max 30 min)…"

while true; do
  status_line=$(gh run list --branch integration/perf-roadmap --limit 5 \
    --json status,conclusion,headSha 2>/dev/null \
    | python3 -c "
import json, sys
runs = json.load(sys.stdin)
target = '$TRIGGER_SHA'
matching = [r for r in runs if r.get('headSha') == target]
if not matching: print('PENDING none'); sys.exit(0)
r = matching[0]
if r.get('status') != 'completed':
  print(f\"PENDING in_progress\")
elif r.get('conclusion') == 'success':
  print('DONE success')
else:
  print(f\"DONE failure conclusion={r.get('conclusion')}\")
")
  case "$status_line" in
    "DONE success")
      echo "OK: CI verification passed for $TRIGGER_SHA"
      exit 0 ;;
    "DONE "*)
      echo "FAIL: CI run for $TRIGGER_SHA: $status_line" >&2
      exit 1 ;;
    "PENDING"*)
      [[ $(date +%s) -ge $DEADLINE ]] && { echo "FAIL: CI run for $TRIGGER_SHA timed out after 30min" >&2; exit 3; }
      sleep 30 ;;
  esac
done
